# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb2f1eb1a48838e5118ddb6f17a33c6e29ef86193330a44912ade12a4ff22b5660a0b4d334fbf40d85ad452c331a4888a622294db05e41dbe0e8cae05d16d498

test:
  secret_key_base: d8cafec9e5734b703ba44be52632344d1e11d8e88d2ef26ca87266579e82c2e7b8f58a6570a50f2e97790d7af606f096e48c74ad21468e2777af600b419000bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
